/**
 * App Redux Action Types
 */
export const COLLAPSED_SIDEBAR = "COLLAPSED_SIDEBAR";
export const DARK_MODE = "DARK_MODE";
export const BOXED_LAYOUT = "BOXED_LAYOUT";
export const RTL_LAYOUT = "RTL_LAYOUT";
export const MINI_SIDEBAR = "MINI_SIDEBAR";
export const SEARCH_FORM_ENABLE = "SEARCH_FORM_ENABLE";
export const CHANGE_THEME_COLOR = "CHANGE_THEME_COLOR";
export const TOGGLE_SIDEBAR_IMAGE = "TOGGLE_SIDEBAR_IMAGE";
export const SET_SIDEBAR_IMAGE = "SET_SIDEBAR_IMAGE";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const START_USER_TOUR = "START_USER_TOUR";
export const STOP_USER_TOUR = "STOP_USER_TOUR";
export const TOGGLE_DARK_SIDENAV = "TOGGLE_DARK_SIDENAV";

// Chat App Actions
export const CHAT_WITH_SELECTED_USER = "CHAT_WITH_SELECTED_USER";
export const SEND_MESSAGE_TO_USER = "SEND_MESSAGE_TO_USER";
export const GET_ALL_CONVERSATION_CHAT = "GET_ALL_CONVERSATION_CHAT";
export const GET_USER_CONVERSATION_CHAT = "GET_USER_CONVERSATION_CHAT";
export const GET_ALL_MESSAGES_CHAT = "GET_ALL_MESSAGES_CHAT";
export const REPLY_CONVERSATION_CHAT = "REPLY_CONVERSATION_CHAT";
export const SET_READ_CONVERSATION_CHAT = "SET_READ_CONVERSATION_CHAT";
export const GET_NEW_MESSAGE_CONVERSATION_CHAT =
  "GET_NEW_MESSAGE_CONVERSATION_CHAT";

//inbox action
export const INBOX_WITH_SELECTED_USER = "INBOX_WITH_SELECTED_USER";
export const INBOX_MESSAGE_TO_USER = "INBOX_MESSAGE_TO_USER";
export const GET_ALL_MESSAGES_INBOX = "GET_ALL_MESSAGES_INBOX";
export const SET_READ_CONVERSATION_INBOX = "SET_READ_CONVERSATION_INBOX";
export const GET_NEW_MESSAGE_CONVERSATION_INBOX =
  "GET_NEW_MESSAGE_CONVERSATION_INBOX";
export const REMOVE_CURRENT_INBOX = "REMOVE_CURRENT_INBOX";
export const REMOVE_CONVERSATION_INLIST_INBOX =
  "REMOVE_CONVERSATION_INLIST_INBOX";
export const OPEN_INBOX = "OPEN_INBOX";
export const REPLY_INBOX_CHAT = "REPLY_INBOX_CHAT";

// Agency Sidebar
export const AGENCY_TOGGLE_MENU = "AGENCY_TOGGLE_MENU";
export const CHANGE_AGENCY_LAYOUT_BG = "CHANGE_AGENCY_LAYOUT_BG";
// Mail App
export const GET_EMAILS = "GET_EMAILS";
export const GET_EMAIL_SUCCESS = "GET_EMAIL_SUCCESS";
export const GET_EMAIL_FAILURE = "GET_EMAIL_FAILURE";
export const SET_EMAIL_AS_STAR = "SET_EMAIL_AS_STAR";
export const READ_EMAIL = "READ_EMAIL";
export const HIDE_LOADING_INDICATOR = "HIDE_LOADING_INDICATOR";
export const FETCH_EMAILS = "FETCH_EMAILS";
export const ON_SELECT_EMAIL = "ON_SELECT_EMAIL";
export const UPDATE_EMAIL_SEARCH = "UPDATE_EMAIL_SEARCH";
export const SEARCH_EMAIL = "SEARCH_EMAIL";
export const ON_DELETE_MAIL = "ON_DELETE_MAIL";
export const ON_BACK_PRESS_NAVIGATE_TO_EMAIL_LISTING =
  "ON_BACK_PRESS_NAVIGATE_TO_EMAIL_LISTING";
export const GET_SENT_EMAILS = "GET_SENT_EMAILS";
export const GET_INBOX = "GET_INBOX";
export const GET_DRAFTS_EMAILS = "GET_DRAFTS_EMAILS";
export const GET_SPAM_EMAILS = "GET_SPAM_EMAILS";
export const GET_TRASH_EMAILS = "GET_TRASH_EMAILS";
export const ON_EMAIL_MOVE_TO_FOLDER = "ON_EMAIL_MOVE_TO_FOLDER";
export const SELECT_ALL_EMAILS = "SELECT_ALL_EMAILS";
export const UNSELECT_ALL_EMAILS = "UNSELECT_ALL_EMAILS";
export const ON_SEND_EMAIL = "ON_SEND_EMAIL";
export const EMAIL_SENT_SUCCESSFULLY = "EMAIL_SENT_SUCCESSFULLY";
export const FILTER_EMAILS_WITH_LABELS = "FILTER_EMAILS_WITH_LABELS";
export const ADD_LABELS_INTO_EMAILS = "ADD_LABELS_INTO_EMAILS";
// sidebar
export const TOGGLE_MENU = "TOGGLE_MENU";
// ToDo App
export const GET_TODOS = "GET_TODOS";
export const FETCH_TODOS = "FETCH_TODOS";
export const ADD_NEW_TASK = "ADD_NEW_TASK";
export const ON_SELECT_TODO = "ON_SELECT_TODO";
export const ON_HIDE_LOADER = "ON_HIDE_LOADER";
export const ON_BACK_TO_TODOS = "ON_BACK_TO_TODOS";
export const ON_SHOW_LOADER = "ON_SHOW_LOADER";
export const MARK_AS_STAR_TODO = "MARK_AS_STAR_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const ADD_LABELS_INTO_THE_TASK = "ADD_LABELS_INTO_THE_TASK";
export const GET_ALL_TODO = "GET_ALL_TODO";
export const GET_COMPLETED_TODOS = "GET_COMPLETED_TODOS";
export const GET_DELETED_TODOS = "GET_DELETED_TODOS";
export const GET_STARRED_TODOS = "GET_STARRED_TODOS";
export const GET_FILTER_TODOS = "GET_FILTER_TODOS";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
export const COMPLETE_TASK = "COMPLETE_TASK";
export const UPDATE_TASK_TITLE = "UPDATE_TASK_TITLE";
export const UPDATE_TASK_DESCRIPTION = "UPDATE_TASK_DESCRIPTION";
export const CHANGE_TASK_ASSIGNER = "CHANGE_TASK_ASSIGNER";
export const ON_CHECK_BOX_TOGGLE_TODO_ITEM = "ON_CHECK_BOX_TOGGLE_TODO_ITEM";
export const SELECT_ALL_TODO = "SELECT_ALL_TODO";
export const GET_UNSELECTED_ALL_TODO = "GET_UNSELECTED_ALL_TODO";
export const SELECT_STARRED_TODO = "SELECT_STARRED_TODO";
export const SELECT_UNSTARRED_TODO = "SELECT_UNSTARRED_TODO";
export const ON_LABEL_SELECT = "ON_LABEL_SELECT";
export const ON_LABEL_MENU_ITEM_SELECT = "ON_LABEL_MENU_ITEM_SELECT";
export const UPDATE_SEARCH = "UPDATE_SEARCH";
export const SEARCH_TODO = "SEARCH_TODO";

// config
export const GET_CONFIG = "GET_CONFIG";
export const SET_CONFIG = "SET_CONFIG";
export const RESET_CONFIG = "RESET_CONFIG";

//assign
export const ASSIGN = "ASSIGN";

// Auth Actions
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAILURE = "SIGNUP_USER_FAILURE";
export const TOKEN_EXPIRED = "TOKEN_EXPIRED";
export const CHECK_TOKEN_SUCCESS = "CHECK_TOKEN_SUCCESS";
export const CHECK_TOKEN_ERROR = "CHECK_TOKEN_ERROR";

//customer action
export const GET_ALL_CUSTOMER = "GET_ALL_CUSTOMER";
export const GET_CUSTOMER_DETAIL = "GET_CUSTOMER_DETAIL";
export const ADD_A_CUSTOMER = "ADD_A_CUSTOMER";
export const UPDATE_A_CUSTOMER_IN_LIST = "UPDATE_A_CUSTOMER_IN_LIST";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const DELETE_A_CUSTOMER_IN_LIST = "DELETE_A_CUSTOMER_IN_LIST";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const SYNC_CUSTOMER_TO_BITRIX24 = "SYNC_CUSTOMER_TO_BITRIX24";

// group action
export const GET_ALL_GROUP = "GET_ALL_GROUP";
export const GET_GROUP_DETAIL = "GET_GROUP_DETAIL";
export const ADD_A_GROUP = "ADD_A_GROUP";
export const UPDATE_GROUP = "UPDATE_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
export const GET_LIST_ASSETS = "GET_LIST_ASSETS";
// asset action
export const GET_ALL_ASSET = "GET_ALL_ASSET";
export const GET_ASSET_DETAIL = "GET_ASSET_DETAIL";
export const ADD_A_ASSET = "ADD_A_ASSET";
export const UPDATE_ASSET = "UPDATE_ASSET";
export const DELETE_ASSET = "DELETE_ASSET";
// category action
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const ADD_A_CATEGORIES = "ADD_A_CATEGORIES";
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_PARENT = "UPDATE_PARENT";
export const GET_ALL_PARENT_WITHOUT_PAGINATE =
  "GET_ALL_PARENT_WITHOUT_PAGINATE";
export const GET_ALL_PARENT = "GET_ALL_PARENT";

// destination action
export const GET_ALL_DESTINATION = "GET_ALL_DESTINATION";
export const ADD_A_DESTINATION = "ADD_A_DESTINATION";
export const UPDATE_DESTINATION = "UPDATE_DESTINATION";
export const DELETE_DESTINATION = "DELETE_DESTINATION";
export const GET_ALL_DESTINATION_PARENT = "GET_ALL_DESTINATION_PARENT";
export const GET_ALL_DESTINATION_WITHOUT_PAGINATE =
  "GET_ALL_DESTINATION_WITHOUT_PAGINATE";
export const GET_ALL_DESTINATION_TYPES = "GET_ALL_DESTINATION_TYPES";
// country action
export const GET_ALL_COUNTRY = "GET_ALL_COUNTRY";
export const ADD_A_COUNTRY = "ADD_A_COUNTRY";
export const UPDATE_COUNTRY = "UPDATE_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY";
export const UPDATE_STATUS_COUNTRY = "UPDATE_STATUS_COUNTRY";

// travel locatoin action
export const GET_ALL_TRAVEL_LOCATION = "GET_ALL_TRAVEL_LOCATION";
export const ADD_A_TRAVEL_LOCATION = "ADD_A_TRAVEL_LOCATION";
export const UPDATE_A_TRAVEL_LOCATION = "UPDATE_A_TRAVEL_LOCATION";
export const DELETE_A_TRAVEL_LOCATION = "DELETE_A_TRAVEL_LOCATION";


// tour action
export const GET_ALL_TOUR = "GET_ALL_TOUR";
export const GET_ALL_TOUR_WITHOUT_PAGINATE = "GET_ALL_TOUR_WITHOUT_PAGINATE";
export const ADD_A_TOUR = "ADD_A_TOUR";
export const UPDATE_TOUR = "UPDATE_TOUR";
export const UPDATE_DEPARTURE_IN_TOUR = "UPDATE_DEPARTURE_IN_TOUR";
export const DELETE_TOUR = "DELETE_TOUR";
export const GET_TOUR_DETAIL = "GET_TOUR_DETAIL";
export const GET_TOUR_RATES = "GET_TOUR_RATES";
export const ADD_TOUR_RATES = "ADD_TOUR_RATES";
export const REMOVE_TOUR_RATE = "REMOVE_TOUR_RATE";
export const UPDATE_TOUR_AIRLINES = "UPDATE_TOUR_AIRLINES";
export const GET_DEPARTURES_OF_TOUR = "GET_DEPARTURES_OF_TOUR";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";

// combo action
export const GET_ALL_COMBO = "GET_ALL_COMBO";
export const GET_ALL_COMBO_WITHOUT_PAGINATE = "GET_ALL_COMBO_WITHOUT_PAGINATE";
export const UPDATE_COMBO = "UPDATE_COMBO";
export const GET_COMBO_DETAIL = "GET_COMBO_DETAIL";


// airline action
export const GET_ALL_AIRLINES = "GET_ALL_AIRLINES";
export const GET_ALL_AIRLINES_WITHOUT_PAGINATE =
  "GET_ALL_AIRLINES_WITHOUT_PAGINATE";
export const ADD_A_AIRLINE = "ADD_A_AIRLINE";
export const UPDATE_AIRLINE = "UPDATE_AIRLINE";
export const DELETE_AIRLINE = "DELETE_AIRLINE";
export const UPDATE_STATUS_AIRLINE = "UPDATE_STATUS_AIRLINE";
export const AIRLINES_BY_TOUR = "AIRLINES_BY_TOUR";

// flight action
export const GET_ALL_FLIGHTS = "GET_ALL_FLIGHTS";
export const ADD_A_FLIGHT = "ADD_A_FLIGHT";
export const UPDATE_FLIGHT = "UPDATE_FLIGHT";
export const DELETE_FLIGHT = "DELETE_FLIGHT";
export const UPDATE_STATUS_FLIGHT = "UPDATE_STATUS_FLIGHT";
export const SEARCH_SABRE_FLIGHTS = "SEARCH_SABRE_FLIGHTS";
export const FLIGHTS_BY_TOUR = "FLIGHTS_BY_TOUR";

// contract action
export const GET_ALL_CONTRACT = "GET_ALL_CONTRACT";
export const ADD_A_CONTRACT = "ADD_A_CONTRACT";
export const UPDATE_CONTRACT = "UPDATE_CONTRACT";
export const DELETE_CONTRACT = "DELETE_CONTRACT";

// ACCOUNT action
export const GET_ALL_ACCOUNT = "GET_ALL_ACCOUNT";
export const GET_ALL_ACCOUNT_WITHOUT_PAGINATE =
  "GET_ALL_ACCOUNT_WITHOUT_PAGINATE";
export const ADD_A_ACCOUNT = "ADD_A_ACCOUNT";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const BATCH_DELETE = "BATCH_DELETE";
export const ACCOUNT_WISHLIST = "ACCOUNT_WISHLIST";
export const GET_DETAIL_ACCOUNT = "GET_DETAIL_ACCOUNT";

//Product type
export const LIST_PRODUCT = "LIST_PRODUCT";
export const LIST_PRODUCT_SUCCESS = "LIST_PRODUCT_SUCCESS";
export const LIST_PRODUCT_ERROR = "LIST_PRODUCT_ERROR";

//Reviews
export const LIST_REVIEW = "LIST_PRODUCT";
export const ADD_REVIEW = "ADD_REVIEW";
export const UPDATE_REVIEW = "UPDATE_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const UPDATE_STATUS_REVIEW = "UPDATE_STATUS_REVIEW";

//Itineraries
export const LIST_ITINERARIES = "LIST_ITINERARIES";
//export const LIST_PRODUCT_SUCCESS = 'LIST_PRODUCT_SUCCESS';
//export const LIST_PRODUCT_ERROR = 'LIST_PRODUCT_ERROR';
export const ADD_ITINERARIES = "ADD_ITINERARIES";
export const UPDATE_ITINERARIES = "UPDATE_ITINERARIES";
export const DELETE_ITINERARIES = "DELETE_ITINERARIES";

//ticket_itineraries
export const LIST_TICKET_ITINERARIES = "LIST_TICKET_ITINERARIES";
export const ADD_TICKET_ITINERARIES = "ADD_TICKET_ITINERARIES";
export const UPDATE_TICKET_ITINERARIES = "UPDATE_TICKET_ITINERARIES";
export const DELETE_TICKET_ITINERARIES = "DELETE_TICKET_ITINERARIES";
// Common type
export const CHANGE_STATUS = "CHANGE_STATUS";
export const PUBLISH_STATUSES = "PUBLISH_STATUSES";
export const UNPUBLISH_STATUSES = "UNPUBLISH_STATUSES";
export const CONSUMER = "CONSUMER";
export const COPY_RECORD = "COPY_RECORD";
export const GET_PAYMENT_ACTION = "GET_PAYMENT_ACTION";

//file manager
export const GET_LIST_FILE_AND_FOLDER = "GET_LIST_FILE_AND_FOLDER";
export const CREATE_FOLDER = "CREATE_FOLDER";
export const UPLOAD_FILE = "UPLOAD_FILE";
export const UPLOAD_IMG = "UPLOAD_IMG";
export const DELETE_FOLDER_FILE = "DELETE_FOLDER_FILE";
export const DOWNLOAD_IMAGE_FROM_URL_TO_SERVER = "DOWNLOAD_IMAGE_FROM_URL_TO_SERVER";
// rules
export const GET_ALL_RULES = "GET_ALL_RULES";
export const ADD_A_RULES = "ADD_A_RULES";
export const UPDATE_RULES = "UPDATE_RULES";
export const DELETE_RULES = "DELETE_RULES";

//currency
export const GET_ALL_CURRENCY = "GET_ALL_CURRENCY";
export const ADD_A_CURRENCY = "ADD_A_CURRENCY";
export const UPDATE_CURRENCY = "UPDATE_CURRENCY";
export const DELETE_CURRENCY = "DELETE_CURRENCY";
export const UPDATE_STATUS_CURRENTCY = "UPDATE_STATUS_CURRENTCY";

//email template
export const GET_ALL_EMAIL = "GET_ALL_EMAIL";
export const ADD_A_EMAIL = "ADD_A_EMAIL";
export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const DELETE_EMAIL = "DELETE_EMAIL";
export const UPDATE_STATUS_EMAIL = "UPDATE_STATUS_EMAIL";

// widgets
export const GET_ALL_WIDGETS = "GET_ALL_WIDGETS";
export const ADD_A_WIDGET = "ADD_A_WIDGET";
export const UPDATE_WIDGET = "UPDATE_WIDGET";
export const DELETE_WIDGET = "DELETE_WIDGET";
export const GET_A_WIDGET = "GET_A_WIDGET";

//orders tour
export const GET_ALL_ORDER_TOUR = "GET_ALL_ORDER_TOUR";
export const GET_ALL_ORDER_HOTEL = "GET_ALL_ORDER_HOTEL";
export const GET_ALL_ORDER_EVENT = "GET_ALL_ORDER_EVENT";
export const GET_ALL_ORDER_COMBO = "GET_ALL_ORDER_COMBO";

export const GET_LIST_ORDER_STAY = "GET_LIST_ORDER_STAY";
export const HANDLE_CANCEL_ORDER_STAY = "HANDLE_CANCEL_ORDER_STAY";
export const HANDLE_CANCEL_ORDER_FLIGHT = "HANDLE_CANCEL_ORDER_FLIGHT";

export const GET_ALL_ORDER_VOUCHER = "GET_ALL_ORDER_VOUCHER";
export const ADD_ORDER_TOUR = "ADD_ORDER_TOUR";
export const ADD_ORDER_VOUCHER = "ADD_ORDER_VOUCHER";
export const UPDATE_PASSENGER = "UPDATE_PASSENGER";
export const DELETE_ORDER_TOUR = "DELETE_ORDER_TOUR";
export const DELETE_ORDER_VOUCHER = "DELETE_ORDER_VOUCHER";
export const GET_DETAIL_ORDER_TOUR = "GET_DETAIL_ORDER_TOUR";
export const UPDATE_ORDER_TOUR = "UPDATE_ORDER_TOUR";
export const UPDATE_ORDER_VOUCHER = "UPDATE_ORDER_VOUCHER";
export const INQUIRY_LIST_ASSIGN = "INQUIRY_LIST_ASSIGN";
export const GET_ORDER_PAYMENT_INFO = "GET_ORDER_PAYMENT_INFO";
export const CANCEL_STAY_ORDER = "CANCEL_STAY_ORDER";
export const CANCEL_ROUTE_ORDER = "CANCEL_ROUTE_ORDER";
export const CANCEL_FLIGHT_ORDER = "CANCEL_FLIGHT_ORDER";

//combo
export const GET_DETAIL_ORDER_COMBO = "GET_DETAIL_ORDER_COMBO";
export const UPDATE_ORDER_COMBO = "UPDATE_ORDER_COMBO";

// notification

//message
export const GET_ALL_MESSAGES = "GET_ALL_MESSAGES";
export const ADD_MESSAGES = "ADD_MESSAGES";
export const UPDATE_MESSAGES = "UPDATE_MESSAGES";
export const DELETE_MESSAGES = "DELETE_MESSAGES";
export const SEND_MESSAGES = "SEND_MESSAGES";
export const GET_ALL_MESSAGES_WITHOUT_PAGINATE =
  "GET_ALL_MESSAGES_WITHOUT_PAGINATE";

//messages
export const GET_ALL_SUBSCRIBERS = "GET_ALL_SUBSCRIBERS";
export const GET_ALL_SUBSCRIBERS_WITHOUT_PAGINATE =
  "GET_ALL_SUBSCRIBERS_WITHOUT_PAGINATE";
// pages
export const GET_ALL_PAGES = "GET_ALL_PAGES";
export const ADD_A_PAGES = "ADD_A_PAGES";
export const UPDATE_PAGES = "UPDATE_PAGES";
export const DELETE_PAGES = "DELETE_PAGES";

// office
export const GET_ALL_OFFICE = "GET_ALL_OFFICE";
export const ADD_A_OFFICE = "ADD_A_OFFICE";
export const UPDATE_OFFICE = "UPDATE_OFFICE";
export const DELETE_OFFICE = "DELETE_OFFICE";
export const GET_ALL_OFFICE_WITHOUT_PAGINATE =
  "GET_ALL_OFFICE_WITHOUT_PAGINATE";

// coupon
export const GET_ALL_COUPON = "GET_ALL_COUPON";
export const ADD_A_COUPON = "ADD_A_COUPON";
export const UPDATE_COUPON = "UPDATE_COUPON";
export const DELETE_COUPON = "DELETE_COUPON";
export const GET_ALL_COUPON_WITHOUT_PAGINATE =
  "GET_ALL_COUPON_WITHOUT_PAGINATE";
export const GIVE_COUPON = "GIVE_COUPON";

// activity
export const GET_ALL_ACTIVITY = "GET_ALL_ACTIVITY";
export const ADD_A_ACTIVITY = "ADD_A_ACTIVITY";
export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
export const GET_ALL_ACTIVITY_WITHOUT_PAGINATE =
  "GET_ALL_ACTIVITY_WITHOUT_PAGINATE";

//hotel
export const GET_ALL_HOTEL = "GET_ALL_HOTEL";
export const ADD_A_HOTEL = "ADD_A_HOTEL";
export const UPDATE_HOTEL = "UPDATE_HOTEL";
export const DELETE_HOTEL = "DELETE_HOTEL";

//inquiry
export const GET_ALL_INQUIRY = "GET_ALL_INQUIRY";
export const ADD_A_INQUIRY = "ADD_A_INQUIRY";
export const UPDATE_INQUIRY = "UPDATE_INQUIRY";
export const DELETE_INQUIRY = "DELETE_INQUIRY";

//ticket
export const GET_ALL_TICKET = "GET_ALL_TICKET";
export const ADD_A_TICKET = "ADD_A_TICKET";
export const UPDATE_TICKET = "UPDATE_TICKET";
export const DELETE_TICKET = "DELETE_TICKET";

//guide calendar
export const GET_ALL_GUIDE_CALENDAR = "GET_ALL_GUIDE_CALENDAR";
export const ADD_A_GUIDE_CALENDAR = "ADD_A_GUIDE_CALENDAR";
export const UPDATE_GUIDE_CALENDAR = "UPDATE_GUIDE_CALENDAR";
export const DELETE_GUIDE_CALENDAR = "DELETE_GUIDE_CALENDAR";
export const GET_CALENDAR_BY_ID = "GET_CALENDAR_BY_ID";

//git
export const GET_ALL_GIT = "GET_ALL_GIT";
export const ADD_A_GIT = "ADD_A_GIT";
export const UPDATE_GIT = "UPDATE_GIT";
export const DELETE_GIT = "DELETE_GIT";

//common app setting action

export const GET_COMMON_APP_SETTING = "GET_COMMON_APP_SETTING";
export const SET_COMMON_APP_SETTING = "SET_COMMON_APP_SETTING";
export const RESET_COMMON_APP_SETTING = "RESET_COMMON_APP_SETTING";

//send message

export const GET_LIST_MESSAGES_CHAT = "GET_LIST_MESSAGES_CHAT";
export const GET_CONVERSATION = "GET_CONVERSATION";
export const SEND_MESSAGES_CHAT = "SEND_MESSAGES_CHAT";
export const GET_LIST_NEW_MESSAGES = "GET_LIST_NEW_MESSAGES";
export const REPLY = "REPLY";
export const RELOAD_MESSAGE = "RELOAD_MESSAGE";

// report
export const REPORT_CUSTOMER_BY_TOUR = "REPORT_CUSTOMER_BY_TOUR";
export const REPORT_FILTER_TOUR_DEPART = "REPORT_FILTER_TOUR_DEPART";
export const EXPORT_EXCEL_CUSTOMER = "EXPORT_EXCEL_CUSTOMER";

// cruise
export const GET_ALL_CRUISES = "GET_LIST_CRUISES";
export const ADD_CRUISE = "ADD_CRUISE";
export const UPDATE_CRUISE = "UPDATE_CRUISE";
export const DELETE_CRUISE = "DELETE_CRUISE";

// stay
export const GET_ALL_AMENITY = "GET_ALL_AMENITY";
export const ADD_A_AMENITY = "ADD_A_AMENITY";
export const UPDATE_AMENITY = "UPDATE_AMENITY";
export const DELETE_AMENITY = "DELETE_AMENITY";
export const GET_A_AMENITY = "GET_A_AMENITY";

export const GET_ALL_RESTAURANT = "GET_ALL_RESTAURANT";
export const ADD_A_RESTAURANT = "ADD_A_RESTAURANT";
export const UPDATE_RESTAURANT = "UPDATE_RESTAURANT";
export const DELETE_RESTAURANT = "DELETE_RESTAURANT";
export const GET_A_RESTAURANT = "GET_A_RESTAURANT";

export const GET_ALL_PROPERTY_TYPE = "GET_ALL_PROPERTY_TYPE";
export const ADD_A_PROPERTY_TYPE = "ADD_A_PROPERTY_TYPE";
export const UPDATE_PROPERTY_TYPE = "UPDATE_PROPERTY_TYPE";
export const DELETE_PROPERTY_TYPE = "DELETE_PROPERTY_TYPE";
export const GET_DETAIL_PROPERTY_TYPE = "GET_DETAIL_PROPERTY_TYPE";

export const GET_ALL_PROPERTY = "GET_ALL_PROPERTY";
export const ADD_A_PROPERTY = "ADD_A_PROPERTY";
export const UPDATE_PROPERTY = "UPDATE_PROPERTY";
export const DELETE_PROPERTY = "DELETE_PROPERTY";
export const GET_DETAIL_PROPERTY = "GET_DETAIL_PROPERTY";
export const ADD_PROPERTY_ROOM_RATE = "ADD_PROPERTY_ROOM_RATE";
export const GET_PROPERTY_ROOM_RATE = "GET_PROPERTY_ROOM_RATE";
export const DELETE_PROPERTY_ROOM_RATE = "DELETE_PROPERTY_ROOM_RATE";
export const UPDATE_PROPERTY_ROOM_RATE = "UPDATE_PROPERTY_ROOM_RATE";
export const UPDATE_MULTI_PROPERTY_ROOM_RATE = "UPDATE_MULTI_PROPERTY_ROOM_RATE";
export const GET_DATA_UTIL = "GET_DATA_UTIL";
export const GET_UTIL_NEAR_BY = "GET_UTIL_NEAR_BY";
export const UPDATE_UTIL_NEAR_BY = "UPDATE_UTIL_NEAR_BY";

export const GET_ALL_ROOM = "GET_ALL_ROOM";
export const ADD_A_ROOM = "ADD_A_ROOM";
export const UPDATE_ROOM = "UPDATE_ROOM";
export const DELETE_ROOM = "DELETE_ROOM";
export const GET_A_ROOM = "GET_A_ROOM";

export const APPROVE = "APPROVE";
export const UNAPPROVE = "UNAPPROVE";

export const GET_ALL_CANCEL_POLICY = "GET_ALL_CANCEL_POLICY";
export const ADD_A_CANCEL_POLICY = "ADD_A_CANCEL_POLICY";
export const UPDATE_CANCEL_POLICY = "UPDATE_CANCEL_POLICY";
export const DELETE_CANCEL_POLICY = "DELETE_CANCEL_POLICY";
export const GET_A_CANCEL_POLICY = "GET_A_CANCEL_POLICY";

export const GET_ALL_CAR = "GET_ALL_CAR";
export const ADD_A_CAR = "ADD_A_CAR";
export const UPDATE_CAR = "UPDATE_CAR";
export const DELETE_CAR = "DELETE_CAR";
export const GET_DETAIL_CAR = "GET_DETAIL_CAR";

export const GET_ALL_ROOM_UTIL_TYPE = "GET_ALL_ROOM_UTIL_TYPE";
export const ADD_A_ROOM_UTIL_TYPE = "ADD_A_ROOM_UTIL_TYPE";
export const UPDATE_ROOM_UTIL_TYPE = "UPDATE_ROOM_UTIL_TYPE";
export const DELETE_ROOM_UTIL_TYPE = "DELETE_ROOM_UTIL_TYPE";
export const GET_DETAIL_ROOM_UTIL_TYPE = "GET_DETAIL_ROOM_UTIL_TYPE";

export const GET_ALL_ROOM_UTIL = "GET_ALL_ROOM_UTIL";
export const ADD_A_ROOM_UTIL = "ADD_A_ROOM_UTIL";
export const UPDATE_ROOM_UTIL = "UPDATE_ROOM_UTIL";
export const DELETE_ROOM_UTIL = "DELETE_ROOM_UTIL";
export const GET_DETAIL_ROOM_UTIL = "GET_DETAIL_ROOM_UTIL";
//permission
export const GET_ALL_ROLE = "GET_ALL_ROLE";
export const CREATE_NEW_ROLE = "CREATE_NEW_ROLE";
export const GET_ALL_PERMISSION_OF_ROLE = "GET_ALL_PERMISSION_OF_ROLE";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const UPDATE_ROLE_USER = "UPDATE_ROLE_USER";
export const GET_ALL_PERMISSION = "GET_ALL_PERMISSION";
export const GET_MY_PERMISSION = "GET_MY_PERMISSION";
export const DELETE_ROLE = "DELETE_ROLE";


//route
export const GET_ALL_ROUTE = "GET_ALL_ROUTE";
export const ADD_A_ROUTE = "ADD_A_ROUTE";
export const UPDATE_ROUTE = "UPDATE_ROUTE";
export const DELETE_ROUTE = "DELETE_ROUTE";
export const GET_ROUTE_DETAIL = "GET_ROUTE_DETAIL";


export const GET_ALL_PROVINCE = "GET_ALL_PROVINCE";
export const GET_ALL_DISTRICT = "GET_ALL_DISTRICT";
export const GET_ALL_WARD = "GET_ALL_WARD";

// newsletter
export const NEWSLETTER_LIST_AUDIENCES = "NEWSLETTER_LIST_AUDIENCES";
export const NEWSLETTER_LIST_MEMBERS = "NEWSLETTER_LIST_MEMBERS";

export const NEWSLETTER_LIST_CAMPAIGNS = "NEWSLETTER_LIST_CAMPAIGN";
export const NEWSLETTER_ADD_CAMPAIGN = "NEWSLETTER_ADD_CAMPAIGN";
export const NEWSLETTER_SEND_CAMPAIGN = "NEWSLETTER_SEND_CAMPAIGN";
export const NEWSLETTER_SCHEDULE_CAMPAIGN = "NEWSLETTER_SCHEDULE_CAMPAIGN";
export const NEWSLETTER_RESEND_CAMPAIGN = "NEWSLETTER_RESEND_CAMPAIGN";
export const NEWSLETTER_DELETE_CAMPAIGN = "NEWSLETTER_DELETE_CAMPAIGN";

export const NEWSLETTER_LIST_TEMPLATES = "NEWSLETTER_LIST_TEMPLATES";

export const NEWSLETTER_LIST_SEGMENTS = "NEWSLETTER_LIST_SEGMENTS";
export const NEWSLETTER_LIST_MEMBERS_SEGMENT = "NEWSLETTER_LIST_MEMBERS_SEGMENT";
export const NEWSLETTER_ADD_SEGMENT = "NEWSLETTER_ADD_SEGMENT";
export const NEWSLETTER_DELETE_SEGMENT = "NEWSLETTER_DELETE_SEGMENT";
export const NEWSLETTER_UPDATE_MEMBERS_SEGMENT = "NEWSLETTER_UPDATE_MEMBERS_SEGMENT";

export const NEWSLETTER_LIST_SUBSCRIBERS = "NEWSLETTER_LIST_SUBSCRIBERS";


// grow hacking
export const GET_ALL_GROWHACKING_CAMPAIGNS = 'GET_ALL_GROWHACKING_CAMPAIGNS';
export const ADD_A_GROWHACKING_CAMPAIGN = 'ADD_A_GROWHACKING_CAMPAIGN';
export const UPDATE_GROWHACKING_CAMPAIGN = 'UPDATE_GROWHACKING_CAMPAIGN';
export const DELETE_GROWHACKING_CAMPAIGN = 'DELETE_GROWHACKING_CAMPAIGN';
export const GET_A_GROWHACKING_CAMPAIGN = 'GET_A_GROWHACKING_CAMPAIGN';

// grow hacking
export const GET_ALL_GROWTH_HACKING_RULES = 'GET_ALL_GROWTH_HACKING_RULES';

//Promotion
export const GET_ALL_PROMOTION = "GET_ALL_PROMOTION";
export const CREATE_NEW_PROMOTION = "CREATE_NEW_PROMOTION";
export const UPDATE_PROMOTION = "UPDATE_ALL_PROMOTION";
export const GET_PROMOTION_DETAIL = "GET_PROMOTION_DETAIL";
export const DELETE_PROMOTION = "DELETE_PROMOTION";

//PROMOTION_PRODUCT
export const GET_ALL_PROMOTION_PRODUCT = "GET_ALL_PROMOTION_PRODUCT";
export const CREATE_NEW_PROMOTION_PRODUCT = "CREATE_NEW_PROMOTION_PRODUCT";
export const UPDATE_PROMOTION_PRODUCT = "UPDATE_ALL_PROMOTION_PRODUCT";
export const GET_PROMOTION_DETAIL_PRODUCT = "GET_PROMOTION_DETAIL_PRODUCT";
export const DELETE_PROMOTION_PRODUCT = "DELETE_PROMOTION_PRODUCT";

// API KEY
export const GET_ALL_API_KEYS = "GET_ALL_API_KEYS";
export const CREATE_NEW_API_KEY = "CREATE_NEW_API_KEY";
export const DELETE_API_KEY = "DELETE_API_KEY";

// Wishlist
export const GET_ALL_WISHLIST = "GET_ALL_WISHLIST";
export const GET_DETAIL_WISHLIST = "GET_DETAIL_WISHLIST";
export const GET_WISHLIST_LOG = "GET_WISHLIST_LOG";
//earning
export const GET_EARNING_OVERVIEW = "GET_EARNING_OVERVIEW";
export const GET_EARNING_DATA = "GET_EARNING_DATA";

export const GET_TRANSACTION = "GET_TRANSACTION";
export const GET_TRANSACTION_DETAIL = "GET_TRANSACTION_DETAIL";
export const TRANSACTION_APPROVE = "TRANSACTION_APPROVE";

//transport order
export const GET_ALL_ORDER_TRANSPORT = "GET_ALL_ORDER_TRANSPORT";
export const UPDATE_ORDER_TRANSPORT = "UPDATE_ORDER_TRANSPORT";
export const DETAIL_ORDER_TRANSPORT = "DETAIL_ORDER_TRANSPORT";
export const HANDLE_CANCEL_ORDER_TRANSPORT = "HANDLE_CANCEL_ORDER_TRANSPORT";

//route service
export const GET_ALL_ROUTE_SERVICE = "GET_ALL_ROUTE_SERVICE";
export const UPDATE_ROUTE_SERVICE = "UPDATE_ROUTE_SERVICE";
export const CREATE_ROUTE_SERVICE = "CREATE_ROUTE_SERVICE";
export const DELETE_ROUTE_SERVICE = "DELETE_ROUTE_SERVICE";

//flight order
export const GET_ALL_ORDER_FLIGHT = "GET_ALL_ORDER_FLIGHT";
export const UPDATE_ORDER_FLIGHT = "UPDATE_ORDER_FLIGHT";
export const DETAIL_ORDER_FLIGHT = "DETAIL_ORDER_FLIGHT";
export const ISSUE_TICKET_ORDER_FLIGHT = "ISSUE_TICKET_ORDER_FLIGHT";

// homepage widgets
export const GET_HOMEPAGE_WIDGETS = "GET_HOMEPAGE_WIDGETS";
export const UPDATE_HOMEPAGE_WIDGETS = "UPDATE_HOMEPAGE_WIDGETS";

// proof
export const CONFIRM_PROOF_OF_PAYMENT = 'CONFIRM_PROOF_OF_PAYMENT';

export const GET_BLOG_CATEGORIES = 'GET_BLOG_CATEGORIES';

// holiday
export const GET_ALL_HOLIDAYS = 'GET_ALL_HOLIDAYS';
export const GET_ALL_HOLIDAY_EXCHANGES = 'GET_ALL_HOLIDAY_EXCHANGES';

//CAR TYPE 
export const GET_ALL_CAR_TYPE = "GET_ALL_CAR_TYPE";
export const ADD_A_CAR_TYPE = "ADD_A_CAR_TYPE";
export const UPDATE_CAR_TYPE = 'UPDATE_CAR_TYPE';
export const DELETE_CAR_TYPE = 'DELETE_CAR_TYPE';

// Utilities hotel
export const GET_LIST_HOTEL_UTILITIES = "GET_LIST_HOTEL_UTILITIES";
export const ADD_HOTEL_UTILITIES = "ADD_HOTEL_UTILITIES";
export const UPDATE_HOTEL_UTILITIES = "UPDATE_HOTEL_UTILITIES";
export const DELETE_HOTEL_UTILITIES = "DELETE_HOTEL_UTILITIES";

// Utilities room
export const GET_LIST_ROOM_UTILITIES = "GET_LIST_ROOM_UTILITIES";
export const ADD_ROOM_UTILITIES = "ADD_ROOM_UTILITIES";
export const UPDATE_ROOM_UTILITIES = "UPDATE_ROOM_UTILITIES";
export const DELETE_ROOM_UTILITIES = "DELETE_ROOM_UTILITIES";

// Manage Pop-up
export const GET_LIST_POPUP = "GET_LIST_POPUP";
export const ADD_POPUP = "ADD_POPUP";
export const UPDATE_POPUP = "UPDATE_POPUP";
export const DELETE_POPUP = "DELETE_POPUP";

// Manage Slider
export const GET_LIST_SLIDER = "GET_LIST_SLIDER";
export const ADD_SLIDER = "ADD_SLIDER";
export const UPDATE_SLIDER = "UPDATE_SLIDER";
export const DELETE_SLIDER = "DELETE_SLIDER";

// Manage Brand
export const GET_LIST_BRAND = "GET_LIST_BRAND";
export const ADD_BRAND = "ADD_BRAND";
export const UPDATE_BRAND = "UPDATE_BRAND";
export const DELETE_BRAND = "DELETE_BRAND";

// Manage Hotel
export const GET_LIST_MANAGE_HOTEL = "GET_LIST_MANAGE_HOTEL";
export const GET_DETAIL_MANAGE_HOTEL = "GET_DETAIL_MANAGE_HOTEL";
export const GET_LIST_ROOM_HOTEL = "GET_LIST_ROOM_HOTEL";
export const ADD_MANAGE_HOTEL = "ADD_MANAGE_HOTEL";
export const UPDATE_MANAGE_HOTEL = "UPDATE_MANAGE_HOTEL";
export const DELETE_MANAGE_HOTEL = "DELETE_MANAGE_HOTEL";
export const VERIFY_MANAGE_HOTEL = "VERIFY_MANAGE_HOTEL";

export const NEW_PRODUCT_COMBO = "NEW_PRODUCT_COMBO";
export const NEW_PRODUCT_TOUR = "NEW_PRODUCT_TOUR";
export const NEW_PRODUCT_VOUCHER = "NEW_PRODUCT_VOUCHER";
export const NEW_PRODUCT_HOTEL = "NEW_PRODUCT_HOTEL";
export const NEW_TRADE_MARK = "NEW_TRADE_MARK";
export const NEW_BLOG = "NEW_BLOG";

// Manage EVENT
export const GET_LIST_MANAGE_EVENT = "GET_LIST_MANAGE_EVENT";
export const ADD_MANAGE_EVENT = "ADD_MANAGE_EVENT";
export const UPDATE_MANAGE_EVENT = "UPDATE_MANAGE_EVENT";
export const DELETE_MANAGE_EVENT = "DELETE_MANAGE_EVENT";
export const VERIFY_MANAGE_EVENT = "VERIFY_MANAGE_EVENT";

// Manage VOUCHER
export const GET_LIST_MANAGE_VOUCHER = "GET_LIST_MANAGE_VOUCHER";
export const ADD_MANAGE_VOUCHER = "ADD_MANAGE_VOUCHER";
export const UPDATE_MANAGE_VOUCHER = "UPDATE_MANAGE_VOUCHER";
export const DELETE_MANAGE_VOUCHER = "DELETE_MANAGE_VOUCHER";
export const VERIFY_MANAGE_VOUCHER = "VERIFY_MANAGE_VOUCHER";
